/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void btnUpClick(GButton source, GEvent event) { //_CODE_:btnUp:855905:
  myPort.write('w');
} //_CODE_:btnUp:855905:

public void btnStopClick(GButton source, GEvent event) { //_CODE_:btnStop:632875:
  myPort.write('x');
} //_CODE_:btnStop:632875:

public void btnDownClick(GButton source, GEvent event) { //_CODE_:btnDown:449039:
  myPort.write('s');
} //_CODE_:btnDown:449039:

public void btnLeftClick(GButton source, GEvent event) { //_CODE_:btnLeft:498010:
  myPort.write('a');
} //_CODE_:btnLeft:498010:

public void btnRightClick(GButton source, GEvent event) { //_CODE_:btnRight:938254:
  myPort.write('d');
} //_CODE_:btnRight:938254:

public void txtAreaChange(GTextArea source, GEvent event) { //_CODE_:txtArea:328944:
  txtArea.appendText("");
} //_CODE_:txtArea:328944:

public void turnCompleteClick(GButton source, GEvent event) { //_CODE_:turnComplete:469513:
  myPort.write('c');
} //_CODE_:turnComplete:469513:

public void rCorridorClick(GButton source, GEvent event) { //_CODE_:rightCorridor:214076:
  myPort.write('r');  
  myPort.write('C');
} //_CODE_:rightCorridor:214076:

public void rRoomClick(GButton source, GEvent event) { //_CODE_:rightRoom:843561:
  myPort.write('r');  
  myPort.write('R');
} //_CODE_:rightRoom:843561:

public void lRoomClick(GButton source, GEvent event) { //_CODE_:leftRoom:259479:
  myPort.write('l');  
  myPort.write('R');
} //_CODE_:leftRoom:259479:

public void lCorridorClick(GButton source, GEvent event) { //_CODE_:leftCorridor:981707:
  myPort.write('l');  
  myPort.write('C');  
} //_CODE_:leftCorridor:981707:

public void enterRoomClick(GButton source, GEvent event) { //_CODE_:enterRoom:724204:
  myPort.write('R'); 
  myPort.write('E');
} //_CODE_:enterRoom:724204:

public void roomExitClick(GButton source, GEvent event) { //_CODE_:roomExit:710831:
  myPort.write('R');  
  myPort.write('L');
} //_CODE_:roomExit:710831:

public void fineTurnRightClick(GButton source, GEvent event) { //_CODE_:fineTurnRight:900490:
  myPort.write('D');
} //_CODE_:fineTurnRight:900490:

public void fineLeftClick(GButton source, GEvent event) { //_CODE_:fineLeft:579491:
  myPort.write('A');
} //_CODE_:fineLeft:579491:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  btnUp = new GButton(this, 100, 51, 80, 30);
  btnUp.setText("UP");
  btnUp.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  btnUp.addEventHandler(this, "btnUpClick");
  btnStop = new GButton(this, 100, 89, 80, 31);
  btnStop.setText("STOP");
  btnStop.setLocalColorScheme(GCScheme.RED_SCHEME);
  btnStop.addEventHandler(this, "btnStopClick");
  btnDown = new GButton(this, 100, 129, 80, 30);
  btnDown.setText("DOWN");
  btnDown.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  btnDown.addEventHandler(this, "btnDownClick");
  btnLeft = new GButton(this, 11, 90, 80, 30);
  btnLeft.setText("LEFT 90");
  btnLeft.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  btnLeft.addEventHandler(this, "btnLeftClick");
  btnRight = new GButton(this, 189, 91, 80, 30);
  btnRight.setText("RIGHT 90");
  btnRight.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  btnRight.addEventHandler(this, "btnRightClick");
  txtArea = new GTextArea(this, 9, 171, 264, 132, G4P.SCROLLBARS_VERTICAL_ONLY | G4P.SCROLLBARS_AUTOHIDE);
  txtArea.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  txtArea.setOpaque(true);
  txtArea.addEventHandler(this, "txtAreaChange");
  turnComplete = new GButton(this, 324, 143, 80, 30);
  turnComplete.setText("Turn Complete");
  turnComplete.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  turnComplete.addEventHandler(this, "turnCompleteClick");
  rightCorridor = new GButton(this, 366, 37, 80, 30);
  rightCorridor.setText("Right Corridor");
  rightCorridor.addEventHandler(this, "rCorridorClick");
  rightRoom = new GButton(this, 366, 88, 80, 30);
  rightRoom.setText("Right Room");
  rightRoom.addEventHandler(this, "rRoomClick");
  leftRoom = new GButton(this, 280, 87, 80, 30);
  leftRoom.setText("Left Room");
  leftRoom.addEventHandler(this, "lRoomClick");
  leftCorridor = new GButton(this, 280, 36, 80, 32);
  leftCorridor.setText("Left Corridor");
  leftCorridor.addEventHandler(this, "lCorridorClick");
  enterRoom = new GButton(this, 278, 196, 80, 30);
  enterRoom.setText("Enter Room");
  enterRoom.addEventHandler(this, "enterRoomClick");
  roomExit = new GButton(this, 365, 197, 80, 30);
  roomExit.setText("Exit Room");
  roomExit.addEventHandler(this, "roomExitClick");
  fineTurnRight = new GButton(this, 204, 58, 45, 30);
  fineTurnRight.setText("RIGHT 10");
  fineTurnRight.addEventHandler(this, "fineTurnRightClick");
  fineLeft = new GButton(this, 31, 56, 37, 30);
  fineLeft.setText("LEFT 10");
  fineLeft.addEventHandler(this, "fineLeftClick");
}

// Variable declarations 
// autogenerated do not edit
GButton btnUp; 
GButton btnStop; 
GButton btnDown; 
GButton btnLeft; 
GButton btnRight; 
GTextArea txtArea; 
GButton turnComplete; 
GButton rightCorridor; 
GButton rightRoom; 
GButton leftRoom; 
GButton leftCorridor; 
GButton enterRoom; 
GButton roomExit; 
GButton fineTurnRight; 
GButton fineLeft; 